# Generated by Django 4.0.5 on 2022-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image_remove_products_image_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(related_name='brand', related_query_name='brand', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='category', related_query_name='category', to='products.brand'),
        ),
    ]
