# Generated by Django 4.0.5 on 2022-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_products_brand_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(null=True, related_name='brand', related_query_name='brand', to='products.brand'),
        ),
    ]
